#!/bin/bash

x=$(id -u)

if [[ $x -ne 0 ]]
then
    echo "mate you need to have root access to install"
    exit 1
else
    echo "you can install this packages"
fi

checking(){
    if [[ $1 -ne 0 ]]
    then
        echo "ERROR:: $2 ...Failed"
        exit 1
    else
        echo "$2... Success"
    fi 
}

read -p "Enter what package you need to install : " package

which ${package}
d = $?
if [[ $d -ne 0 ]]
then
    apt-get install ${package} -y
else
    echo "package ${package} already installed in this system"